# Generated by Django 3.2.10 on 2024-09-21 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_description', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
