name: Deploy to Expo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install dependencies
        run: cd taskhola-mobile && npm install

      - name: Build the project
        run: cd taskhola-mobile && npm run build 

      - name: Deploy to Expo
        run: cd taskhola-mobile && npx expo-cli deploy:ios && npx expo-cli deploy:android
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  