name: Deploy Backend to Ubuntu Server

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to Ubuntu Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PASS: ${{ secrets.SERVER_PASS }}
      run: |
        sshpass -p $PASS scp -o StrictHostKeyChecking=no -r backend/* ${USER}@${HOST}:/path/to/backend/
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /path/to/backend
          docker-compose down
          docker-compose up -d --build
        '

    - name: Clean up
      run: sudo apt-get remove sshpass
