name: Deploy App to Appetize

on:
  push:
    branches:
      - main
    paths:
      - 'taskhola-mobile/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd taskhola-mobile
        npm install

    - name: Build app
      run: |
        cd taskhola-mobile
        npm run build

    - name: Upload to Appetize
      uses: appetizeio/github-action-appetize@v1.0.3
      with:
        apiToken: ${{ secrets.APPETIZE_API_TOKEN }}
        appFile: taskhola-mobile/build/app.zip

    - name: Cleanup
      run: rm -rf taskhola-mobile/build

